### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by filmaj** [adobe/angle#1]
Hello,
My name is Fil and I’m from Adobe’s Open Source Office. I see this project has been inactive for a long time. Just wondering: is there still value in keeping this project around? Do we foresee community usage/activity happening around this project?

If yes, can I send some pull requests to update the documentation? At a minimum we need contribution guidelines that reference requiring the signing of [Adobe’s CLA](http://opensource.adobe.com/cla.html). It would be nice if this project also had a README. Finally, what license does it use? I can't tell from the existing license file.

If no, is it OK if we archive this project?

Thanks for any info.

-Fil

**Comment by mvujovic** [comment]
Please feel free to archive this project; it's inactive. It was a copy of the public ANGLE project, hosted elsewhere on GitHub. I'm not sure why it wasn't a fork in the first place.

Thanks,
Max

**Comment by filmaj** [comment]
Thank you for the response! I've added a readme with the state made explicit in there and will archive it shortly.
